apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: amemni-cluster
servers: 1
agents: 2
registries:
  create:
    name: amemni-registry
    host: 0.0.0.0
    hostPort: '5000'
ports:
  - port: 8000:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
  kubeconfig:
    updateDefaultKubeconfig: true